service: devlog-server

plugins:
  - serverless-webpack
  - serverless-dotenv-plugin
  - serverless-offline

custom:
  webpack:
    includeModules: true

provider:
  name: aws
  runtime: nodejs12.x
  region: ap-northeast-2
  stage: dev
  lambdaHashingVersion: 20201221
  apiGateway:
    shouldStartNameWithService: true
  

  environment:
    SECRET_KEY: ${env:SECRET_KEY}
    DB_HOST: ${env:DB_HOST}
    DB_PORT: ${env:DB_PORT}
    DB_USERNAME: ${env:DB_USERNAME}
    DB_DATABASE: ${env:DB_DATABASE}
    DB_PASSWORD: ${env:DB_PASSWORD}

  # iamRoleStatements:
  #   - Effect: Allow
  
  vpc:
    securityGroupIds:
      - ${env:AWS_SECURITY_GROUP_ID}
    subnetIds:
      - ${env:AWS_SUBNET_ID_FIRST}
      - ${env:AWS_SUBNET_ID_SECOND}
      - ${env:AWS_SUBNET_ID_THIRD}

unresolvedVariablesNotificationMode: error

functions:
  app:
    handler: src/serverless.handler
    environment:
      SLS_DEBUG: ${env:SERVERLESS_DEBUG}
    events:
      - http:
          path: /
          method: ANY
      - http:
          path: /{any+}
          method: ANY