service:
  name: 'blog-server'

plugins:
  - serverless-webpack
  - serverless-offline

custom:
  webpack:
    includeModules: true

provider:
  name: aws
  runtime: nodejs12.x
  region: ap-northeast-2
  stage: dev

functions:
  app:
    handler: src/serverless.handler
    environment:
      SLS_DEBUG: true
    events:
      - http:
          path: /
          method: ANY
      - http:
          path: /{any+}
          method: ANY